### ISSUE TITLE
Integrating CI Tools

### ISSUE THREAD

**Issue by yim0331** [Argonne-National-Laboratory/MaximinOPF.jl#23]
We can integrate the CI tools to show the status of the project.

We may be able to use Github's basic CI tools for building and documentation.

**Comment by kibaekkim** [comment]
I have added a github action, as you suggested. Can you take a look at it?

**Comment by yim0331** [comment]
@kibaekkim Could you give the travis, https://travis-ci.org/, to access our repository? I added travis config file for CI, but my permission is not enough to enable the travis in MaximinOPF.

**Comment by kibaekkim** [comment]
@yim0331 How is this different from Julia TagBot of Github Actions? Could this be done through Julia TagBot?

**Comment by yim0331** [comment]
@kibaekkim This is much simpler than Julia TagBot. You can simply sign-on, login, and give Trivs the github access permission. Julia TagBot can't connect to the Travis CI tool. TagBot is for the julia package management and the Travis is for the build automation to show the status of the repository.

**Comment by kibaekkim** [comment]
Done. Thanks for the help, @yim0331
