### ISSUE TITLE
Missing function: add_psd_initial_cuts

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/MaximinOPF.jl#25]
The function is not defined: https://github.com/Argonne-National-Laboratory/MaximinOPF.jl/blob/master/src/utils.jl#L164

**Comment by kibaekkim** [comment]
Found it here: https://github.com/Argonne-National-Laboratory/MaximinOPF.jl/commit/e1e4db3ee67395817f3da027fdd0a43dbf16c95c#diff-de08f51fe93b9406046593271d4e89c3L91-L102

**Comment by kibaekkim** [comment]
I also found that this function is gone too: `add_artificial_var_bds`

**Comment by kibaekkim** [comment]
I could simply copy and paste many missing functions from old commit. But, there is a missing variable `psd_expr_lbs` in https://github.com/Argonne-National-Laboratory/MaximinOPF.jl/commit/e1e4db3ee67395817f3da027fdd0a43dbf16c95c#diff-de08f51fe93b9406046593271d4e89c3L100

**Comment by bcdandurand** [comment]
For now, I'm removing any functions adding psd cone supporting constraints or artificial bounds from `src/utils.jl` of the `master` branch. I might add this functionality back to `master` later, but the issues I tried to address with these functions should be addressed on the solver (scipsdp) end, and we can provide the scipsdp developers a clearer picture of the reasons their code seems to not work  properly for some instances later.
