### ISSUE TITLE
runtests.jl and examples with SCS

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/MaximinOPF.jl#26]
Since `Mosek` is commercial, it is not the best one to use for the public release. Let's use `SCS` for solving the continuous relaxation, for example
```julia
model=MaximinOPF.MaximinOPFModel(pm_data, SparseSDPWRMPowerModel; enforce_int=false)
```
Note that we use `enforce_int=false`.

**Comment by kibaekkim** [comment]
@yim0331 Can you take care of this? And integrate with Actions? #23

**Comment by yim0331** [comment]
@kibaekkim The SCS solver is not supporting some constraints that we use.
For the SOC and SDP cases, I'm having the following errors:
Start Solving: case9SOCWR1
ERROR: LoadError: MathOptInterface.UnsupportedConstraint{MathOptInterface.SingleVariable,MathOptInterface.Integer}: `MathOptInterface.SingleVariable`-in-`MathOptInterface.Integer` constraint is not supported by the model.

Start Solving: case9SDPWR1
ERROR: LoadError: MathOptInterface.UnsupportedConstraint{MathOptInterface.SingleVariable,MathOptInterface.Integer}: `MathOptInterface.SingleVariable`-in-`MathOptInterface.Integer` constraint is not supported by the model.

I think it would be okay for now to keep the solver parts as comments to indicate user how to use this model.

**Comment by kibaekkim** [comment]
Can you put some example? I was able to run the following script:
```julia
using MaximinOPF
using PowerModels
using JuMP
using SCS
instance="case9"
PowerModels.silence()
pm_data = PowerModels.parse_file("../data/$(instance).m")
pm_data["attacker_budget"] = 4
pm_data["inactive_branches"] = []
pm_data["protected_branches"] = []
model=MaximinOPF.MaximinOPFModel(pm_data, SparseSDPWRMPowerModel; enforce_int=false)
soc_solver = SCS.Optimizer
JuMP.set_optimizer(model, soc_solver)
JuMP.optimize!(model)
@show JuMP.termination_status(model)
@show JuMP.objective_value(model)
```

**Comment by yim0331** [comment]
@kibaekkim  Thank you for the test script. The SCS solver is working well with the option "; enforce_int=false"

**Comment by kibaekkim** [comment]
@yim0331 you can close this, if you think done.

**Comment by kibaekkim** [comment]
I see this is done.
