### ISSUE TITLE
Test script needs to test file writing

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/MaximinOPF.jl#27]
The test script should test writing files fro CBF and SDPA formats. The current file write functions are not working, although the commit comment says test passed. 
Related to #26

**Comment by kibaekkim** [comment]
I have reported bugs for both CBF and SDPA writers in MOI. 
- Several fixes for SDPA format have already been made and pushed to the `master` branch and will be ported to `0.9.14`.
- I do not see any fix for CBF format yet.

**Comment by bcdandurand** [comment]
CBF format is tested in test/runtests.jl as of last push to master. 

I haven't looked at what has been done with SDPA format yet, and these are not in test yet, so I'm keeping the issue open.

**Comment by kibaekkim** [comment]
I have pushed the updated test scripts. I decided to use JuMP functions for writing files. So we don't need to test it in our package.
