### ISSUE TITLE
Return of MinimaxOPFModel

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/MaximinOPF.jl#29]
Is there any reason that `MinimaxOPFModel` returns `PowerModels` instead of `JuMP.Model`? Function `MaximinOPFModel` returns a `JuMP.Model`.

**Comment by bcdandurand** [comment]
Returning the `Powermodels` instance allows the user not just access to the model, but to the other attributes of the `Powermodels` instance that is also created. Denoting the return value `pm`, the user would access the model with `pm.model`.

On the other hand, in creating the Maxmin problem, `dualization()` is applied to the same model that would be returned by `MinimaxOPFModel()`, and naturally there is no `Powermodels` instance associated with the dualized `JuMP.Model` instance. 

One possibility might be to have both functions return the `PowerModels` instance that is created, if the `MaximinOPFModel` function could create an attribute like `pm.dual_model`.

If the idea is to keep the `PowerModels` interface under the hood, then both functions should just return instances of `JuMP.Model`. 

While I lean more toward the former approach of having both functions return `PowerModels` instances with the desired model instantiated as an attribute, it's not perfectly clear to me which way to go.

**Comment by kibaekkim** [comment]
OK. I think the current implementation makes sense then. Let's not take any further action on this.
